### ISSUE TITLE
Ability to clear the presence after a set duration of listening inactivity?

### ISSUE THREAD

**Issue by TastelessTacos** [RegorForgot/LastfmDiscordRPC#3]
I noticed that the the presence pulls whatever the current last.fm song data is, whether it is currently playing or played a song let's say an hour ago. This status will show as long as the RPC app is running.

Is there a possibility to have it clear the presence when a set duration is passed without any listening activity?

**Comment by RegorForgot** [comment]
Yes; this is doable. I'm currently in assignment season sadly and so I won't be able to add this functionality just yet, but I reckon I can fit it in within a week or two. Thanks for the suggestion!

**Comment by RegorForgot** [comment]
Implemented in ![v1.2.0](https://github.com/RegorForgot/LastfmDiscordRPC/releases/tag/1.2.0)
