### ISSUE TITLE
Unhandled exception after few minutes from stopped listening music

### ISSUE THREAD

**Issue by hsl-sv** [RegorForgot/LastfmDiscordRPC#8]
+ [2024-11-14 10:38:58] INFO: Track successfully received! Attempting to connect to presence...
+ [2024-11-14 10:38:58] INFO: Presence has been set!
+ [2024-11-14 10:42:31] ERR : Last.fm OperationFail: Operation failed - Most likely the backend service failed. Please try again.
+ [2024-11-14 10:42:31] INFO: Attempting to reconnect... Try 1
+ [2024-11-14 11:11:57] ERR : HTTP 0: Exception of type 'System.Net.Http.HttpRequestException' was thrown.
+ [2024-11-14 11:11:57] INFO: Attempting to reconnect... Try 1
+ [2024-11-14 11:20:23] ERR : Last.fm OperationFail: Operation failed - Most likely the backend service failed. Please try again.
+ [2024-11-14 11:20:23] INFO: Attempting to reconnect... Try 1
+ [2024-11-14 11:25:04] ERR : Last.fm OperationFail: Operation failed - Most likely the backend service failed. Please try again.
+ [2024-11-14 11:25:04] INFO: Attempting to reconnect... Try 1
+ [2024-11-14 11:41:23] ERR : Last.fm OperationFail: Operation failed - Most likely the backend service failed. Please try again.
+ [2024-11-14 11:41:23] INFO: Attempting to reconnect... Try 1
+ [2024-11-14 11:41:25] ERR : Last.fm OperationFail: Operation failed - Most likely the backend service failed. Please try again.
+ [2024-11-14 11:41:25] INFO: Attempting to reconnect... Try 2
+ [2024-11-14 11:43:06] ERR : Unhandled exception! Please report to developers
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at LastfmDiscordRPC2.Models.API.LastfmAPIService.GetResponse[T](RestResponseBase response)
   at LastfmDiscordRPC2.Models.API.LastfmAPIService.GetRecentTracks(String username)
   at LastfmDiscordRPC2.Models.RPC.PresenceService.PresenceLoop(SaveCfg saveSnapshot)
+ [2024-11-14 11:43:06] INFO: Presence has been expired.

I stopped music at 10:55 AM, after few minutes, presence disabled by error, it happened several times.

**Comment by RegorForgot** [comment]
Thanks for bringing this issue to my attention. Honestly, last.fm has been having some trouble with its servers lately (especially yesterday) and I've noticed that certain features (like the now-playing functionaltiy) were entirely dead for a lot of yesterday. 

It seems like there were some server issues too while you were using the application, given how many times Last.fm decided to throw an OperationFail error through the server. I think what happened is that Last.fm tried to send back a response but the server probably just died halfway through and the response became malformed. I'll see what I can do to handle this case.

**Comment by RegorForgot** [comment]
Should be fixed in #[2.2.1 ](https://github.com/RegorForgot/LastfmDiscordRPC/releases/tag/2.2.1). Let me know how that works for you

**Comment by hsl-sv** [comment]
It working perfectly, thanks a lot :))
